-- AttuneNext static open-world zone data
-- zone = AreaTable zoneId (used directly with ItemLocGetAllItemsInZone / ItemLocItemIsInZone)
-- exp: 1=Classic 2=TBC 3=WotLK    city=true: shown for Vendor browsing only
local _, ANx = ...
ANx = ANx or _G.AttuneNext

ANx.Zones = {
    -- ============================ CLASSIC: EASTERN KINGDOMS ============================
    { name = "Elwynn Forest",        zone = 12,   exp = 1 },
    { name = "Westfall",             zone = 40,   exp = 1 },
    { name = "Redridge Mountains",   zone = 44,   exp = 1 },
    { name = "Duskwood",             zone = 10,   exp = 1 },
    { name = "Stranglethorn Vale",   zone = 33,   exp = 1 },
    { name = "Swamp of Sorrows",     zone = 8,    exp = 1 },
    { name = "Blasted Lands",        zone = 4,    exp = 1 },
    { name = "Deadwind Pass",        zone = 41,   exp = 1 },
    { name = "Burning Steppes",      zone = 46,   exp = 1 },
    { name = "Searing Gorge",        zone = 51,   exp = 1 },
    { name = "Badlands",             zone = 3,    exp = 1 },
    { name = "Loch Modan",           zone = 38,   exp = 1 },
    { name = "Dun Morogh",           zone = 1,    exp = 1 },
    { name = "Wetlands",             zone = 11,   exp = 1 },
    { name = "Arathi Highlands",     zone = 45,   exp = 1 },
    { name = "Hillsbrad Foothills",  zone = 267,  exp = 1 },
    { name = "Alterac Mountains",    zone = 36,   exp = 1 },
    { name = "Silverpine Forest",    zone = 130,  exp = 1 },
    { name = "Tirisfal Glades",      zone = 85,   exp = 1 },
    { name = "Western Plaguelands",  zone = 28,   exp = 1 },
    { name = "Eastern Plaguelands",  zone = 139,  exp = 1 },
    { name = "The Hinterlands",      zone = 47,   exp = 1 },
    -- ============================ CLASSIC: KALIMDOR ============================
    { name = "Durotar",              zone = 14,   exp = 1 },
    { name = "The Barrens",          zone = 17,   exp = 1 },
    { name = "Mulgore",              zone = 215,  exp = 1 },
    { name = "Stonetalon Mountains", zone = 406,  exp = 1 },
    { name = "Ashenvale",            zone = 331,  exp = 1 },
    { name = "Teldrassil",           zone = 141,  exp = 1 },
    { name = "Darkshore",            zone = 148,  exp = 1 },
    { name = "Azshara",              zone = 16,   exp = 1 },
    { name = "Felwood",              zone = 361,  exp = 1 },
    { name = "Winterspring",         zone = 618,  exp = 1 },
    { name = "Moonglade",            zone = 493,  exp = 1 },
    { name = "Desolace",             zone = 405,  exp = 1 },
    { name = "Feralas",              zone = 357,  exp = 1 },
    { name = "Dustwallow Marsh",     zone = 15,   exp = 1 },
    { name = "Thousand Needles",     zone = 400,  exp = 1 },
    { name = "Tanaris",              zone = 440,  exp = 1 },
    { name = "Un'Goro Crater",       zone = 490,  exp = 1 },
    { name = "Silithus",             zone = 1377, exp = 1 },
    -- ============================ CLASSIC: CITIES ============================
    { name = "Stormwind City",       zone = 1519, exp = 1, city = true },
    { name = "Ironforge",            zone = 1537, exp = 1, city = true },
    { name = "Darnassus",            zone = 1657, exp = 1, city = true },
    { name = "Orgrimmar",            zone = 1637, exp = 1, city = true },
    { name = "Thunder Bluff",        zone = 1638, exp = 1, city = true },
    { name = "Undercity",            zone = 1497, exp = 1, city = true },

    -- ============================ TBC ============================
    { name = "Eversong Woods",       zone = 3430, exp = 2 },
    { name = "Ghostlands",           zone = 3433, exp = 2 },
    { name = "Azuremyst Isle",       zone = 3524, exp = 2 },
    { name = "Bloodmyst Isle",       zone = 3525, exp = 2 },
    { name = "Hellfire Peninsula",   zone = 3483, exp = 2 },
    { name = "Zangarmarsh",          zone = 3521, exp = 2 },
    { name = "Terokkar Forest",      zone = 3519, exp = 2 },
    { name = "Nagrand",              zone = 3518, exp = 2 },
    { name = "Blade's Edge Mountains", zone = 3522, exp = 2 },
    { name = "Netherstorm",          zone = 3523, exp = 2 },
    { name = "Shadowmoon Valley",    zone = 3520, exp = 2 },
    { name = "Isle of Quel'Danas",   zone = 4080, exp = 2 },
    { name = "Silvermoon City",      zone = 3487, exp = 2, city = true },
    { name = "The Exodar",           zone = 3557, exp = 2, city = true },
    { name = "Shattrath City",       zone = 3703, exp = 2, city = true },

    -- ============================ WOTLK ============================
    { name = "Borean Tundra",        zone = 3537, exp = 3 },
    { name = "Howling Fjord",        zone = 495,  exp = 3 },
    { name = "Dragonblight",         zone = 65,   exp = 3 },
    { name = "Grizzly Hills",        zone = 394,  exp = 3 },
    { name = "Zul'Drak",             zone = 66,   exp = 3 },
    { name = "Sholazar Basin",       zone = 3711, exp = 3 },
    { name = "Crystalsong Forest",   zone = 2817, exp = 3 },
    { name = "The Storm Peaks",      zone = 67,   exp = 3 },
    { name = "Icecrown",             zone = 210,  exp = 3 },
    { name = "Wintergrasp",          zone = 4197, exp = 3 },
    { name = "Dalaran",              zone = 4395, exp = 3, city = true },
}
