-- =========================================================================
-- AttuneNext - RunTimer.lua (retired)
--
-- The addon no longer times your runs. Personal clear times come only from
-- Synastria's Dungeon Challenge buff, which is read in SpeedAura.lua.
-- This file is not loaded (see AttuneNext.toc) and can be deleted.
-- =========================================================================
